services:
  - type: web
    name: mood-vibecheck-bot
    runtime: go
    repo: https://github.com/katshuuu/mood-vibecheck-bot
    branch: main
    buildCommand: go build -o mood-bot
    startCommand: ./mood-bot
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false  # Токен будет вводиться вручную
      - key: PORT
        value: 8080